---
name: Module-Starter-Plugin-CGIApp
version: 0.10
author:
  - 'Jaldhar H. Vyas <jaldhar@braincells.com>'
abstract: template based module starter for CGI apps.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  ExtUtils::Command: 0
  File::Basename: 0
  File::Spec: 0
  HTML::Template: 0
  Module::Starter: 0
build_requires:
  ExtUtils::Command: 0
  File::Spec: 0
  Module::Signature: 0
  Pod::Coverage: 0.18
  Pod::Usage: 0
  Test::More: 0
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
provides:
  Module::Starter::Plugin::CGIApp:
    file: lib/Module/Starter/Plugin/CGIApp.pm
    version: 0.10
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
